In [2]:
import pandas as pd

In [5]:
ecology = pd.read_csv('../../Body/2Derived/NematodesFromEcologyToGenetics.csv')

In [6]:
ecology

,PC1 projection FourFoldPCA (from r strategy to K strategy),Species,Group (Family),Taxonomy,"cp scaling (1 - colonizer, 5 - persister)","Type (free, parasite, facultative)",Feeding (based on Family),"Main host (vertebrate, plant, aquatic, invertebrate, insect)",All hosts,Host organs,"Temperature of environment (for parasite - temp of host, warm/cold)","Aerobic environment (aerobic, anaerobic)",Average time from egg to egg,Fertility (number of eggs per lifetime OR per clutch OR per day),Adult body size (length),intermediate <=> final host,Comment / life cycle,link to life-cycle,sex
0,-2.35,Dirofilaria repens,Paratylenchus,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"dogs, cats",heart,NaN,NaN,NaN,NaN,NaN,mosquito => dog,infected mosquito [numerous == r?] introduces ...,https://www.cdc.gov/parasites/dirofilariasis/b...,NaN
1,-2.20,Parastrongyloides trichosuri,Strongyloididae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,NaN,animal parasites,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,free <=> parasite,"a nematode parasite of mammals, Parastrongyloi...",https://pubmed.ncbi.nlm.nih.gov/16500655/,NaN
2,-2.20,Dirofilaria sp. hongkongensis,Onchocercidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"dogs, humans","heart, lungs",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-2.18,Strongyloides stercoralis,Strongyloididae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"humans, mammals",small intestine,NaN,NaN,NaN,NaN,NaN,free <=> parasite,сложным и уникальным для нематод циклом развит...,https://ru.wikipedia.org/wiki/Strongyloides_st...,NaN
4,-2.18,Setaria digitata,Setariidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"cattle, sheep, goats, pigs, horses",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,5.13,Trichinella murrelli,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mammals <=> mammals,Adult worms and encysted larvae develop within...,https://www.cdc.gov/parasites/trichinellosis/b...,NaN
180,5.23,Trichinella nelsoni,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mammals <=> mammals,Adult worms and encysted larvae develop within...,https://www.cdc.gov/parasites/trichinellosis/b...,NaN
181,5.37,Trichinella nativa,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mammals <=> mammals,Adult worms and encysted larvae develop within...,https://www.cdc.gov/parasites/trichinellosis/b...,NaN
182,5.42,Trichinella spiralis,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mammals <=> mammals,Adult worms and encysted larvae develop within...,https://www.cdc.gov/parasites/trichinellosis/b...,NaN
183,5.50,Trichinella pseudospiralis,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mammals <=> mammals,Adult worms and encysted larvae develop within...,https://www.cdc.gov/parasites/trichinellosis/b...,Females are 2.2 mm in length; males 1.2 mm

In [5]:
clc_hosts = pd.read_csv('../../Body/2Derived/CLC_database_hosts.csv')

In [6]:
clc_hosts

,Parasite.species,Parasite.genus,Parasite.group,Host.species,Host.common.name,Missing.info,Typical.host,Host.no,Def.int,Facultative,...,Asexual,Site,Host.habitat,Vert.group,Remark,Author,Year,Journal,Volume,Pages
0,Abbreviata antarctica,Abbreviata,nematode,Acheta domesticus,cricket,0,atypical,1,int,no,...,none,gut wall,terrestrial,NaN,only found in one of exposed hosts,King et al.,2013.0,J. Parasitol.,99,708-711
1,Abbreviata antarctica,Abbreviata,nematode,Teleogryllus oceanicus,cricket,0,typical,1,int,no,...,none,gut wall,terrestrial,NaN,also exposed two roach species and a termite,King et al.,2013.0,J. Parasitol.,99,708-711
2,Abbreviata antarctica,Abbreviata,nematode,Austrelaps superbus,snake,0,atypical,2,def,no,...,none,gut,terrestrial,herp,NaN,Jones,2014.0,Aust. J. Zool.,62,180-194
3,Abbreviata antarctica,Abbreviata,nematode,Denisonia fasciata,snake,0,atypical,2,def,no,...,none,gut,terrestrial,herp,less typical of snakes,Jones,2014.0,Aust. J. Zool.,62,180-194
4,Abbreviata antarctica,Abbreviata,nematode,Drysdalia coronata,snake,0,atypical,2,def,no,...,none,gut,terrestrial,herp,NaN,Jones,2014.0,Aust. J. Zool.,62,180-194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8599,Wardium stellorae,Wardium,cestode,Artemia parthenogenetica,brine shrimp,0,typical,1,int,no,...,none,body cavity,freshwater,NaN,likely closely allied to Branchiopodataenia,Georgiev et al.,2005.0,Acta Parasitol.,50,105-117
8600,Wardium stellorae,Wardium,cestode,Artemia salina,brine shrimp,0,typical,1,int,no,...,none,body cavity,freshwater,NaN,NaN,Georgiev et al.,2005.0,Acta Parasitol.,50,105-117
8601,Wardium stellorae,Wardium,cestode,Chroicocephalus genei,slender-billed gull,0,typical,2,def,no,...,none,gut,freshwater,bird,NaN,Ryzhikov et al.,1985.0,Helminths of fish-eating birds of the Palaearc...,NaN,NaN
8602,Wardium stellorae,Wardium,cestode,Chroicocephalus ridibundus,black-headed gull,0,typical,2,def,no,...,none,gut,freshwater,bird,NaN,Ryzhikov et al.,1985.0,Helminths of fish-eating birds of the Palaearc...,NaN,NaN
8603,Wardium stellorae,Wardium,cestode,Larus californicus,california gull,0,typical,2,def,no,...,none,gut,freshwater,bird,NaN,Keppner,1973.0,Trans. Am. Microsc. Soc.,92,288-291

In [24]:
clc_hosts_agg = clc_hosts.groupby(['Parasite.species', 'Parasite.genus', 'Parasite.group']).agg(lambda x: list(x)).reset_index()

In [8]:
clc_lifehistory = pd.read_csv('../../Body/2Derived/CLC_database_lifehistory.csv')

In [9]:
clc_lifehistory

,Parasite.species,Parasite.genus,Parasite.group,Host.species,Host.no,Stage,Egg.hatch,Development.time,Temp,Development.remarks,...,Size.reported.as,Shape,Asexual,Sex,Size.remarks,Author,Year,Journal,Volume,Pages
0,Abbreviata antarctica,Abbreviata,nematode,NaN,0,egg,eaten,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abbreviata antarctica,Abbreviata,nematode,NaN,0,embryo,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abbreviata antarctica,Abbreviata,nematode,Teleogryllus oceanicus,1,1larv,NaN,25.5,28.0,NaN,...,range,thread-like,NaN,NaN,NaN,King et al.,2013.0,J. Parasitol.,99,708-711
3,Abbreviata antarctica,Abbreviata,nematode,NaN,2,adult,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abbreviata caucasica,Abbreviata,nematode,NaN,0,egg,eaten,NaN,NaN,NaN,...,range,ellipsoid,NaN,NaN,additional 'gelatinous deposit' around the egg,Poinar and Quentin,1972.0,J. Parasitol.,58,23-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10005,Wardium stellorae,Wardium,cestode,Artemia salina,1,1larv,NaN,NaN,NaN,NaN,...,range,sphere,NaN,NaN,NaN,Maksimova,1990.0,Parazitologiya,24,89-92
10006,Wardium stellorae,Wardium,cestode,Artemia salina,1,1larv,NaN,NaN,NaN,NaN,...,point,sphere,NaN,NaN,NaN,Robert and Gabrion,1991.0,Ann. Parasitol. Hum. Comp.,66,226-235
10007,Wardium stellorae,Wardium,cestode,Chroicocephalus genei,2,adult,NaN,NaN,NaN,NaN,...,range,ribbon,NaN,NaN,NaN,Maksimova,1986.0,Parazitologiya,20,487-491
10008,Wardium stellorae,Wardium,cestode,Chroicocephalus ridibundus,2,adult,NaN,NaN,NaN,NaN,...,point,ribbon,NaN,NaN,NaN,Maksimova,1986.0,Parazitologiya,20,487-491
10009,Wardium stellorae,Wardium,cestode,NaN,2,adult,NaN,NaN,NaN,NaN,...,range,ribbon,NaN,NaN,NaN,Ryzhikov et al.,1985.0,Helminths of fish-eating birds of the Palaearc...,NaN,NaN

In [26]:
clc_lifehistory_agg = clc_lifehistory.groupby(['Parasite.species', 'Parasite.genus', 'Parasite.group']).agg(lambda x: list(x)).reset_index()

In [13]:
nemaplex = pd.read_csv('../../Body/2Derived/nemaplex.csv', sep=';')

In [14]:
nemaplex

,Species,Family,PutativeFeeding,Cpscaling,FeedingGroup,FunctionalGuild,InternalCode
0,Abathymermis,Mermithidae,animal parasites,,,,
1,Abbreviata,Physalopteridae,animal parasites,,,,
2,Abelbolla,Enchelidiidae,marine nematodes,,,,
3,Abirovulva,Carnoyidae,animal parasites,,,,
4,Ablechroiulus,Rhabditidae,bacteria feeders,1,3,b1,G2211mnu.htm
...,...,...,...,...,...,...,...
1814,Zetalaimus,Leptonchidae,fungus feeders,4,2,f4,G7791mnu.htm
1815,Zullinius,Odontopharyngidae,predators,1,5,p1,
1816,Zygonemella,Xyalidae,marine nematodes,,,,
1817,Zygotylenchus,Pratylenchidae,plant feeders,3,1,h3,G144mnu.htm
1818,Zygradus,Pratylenchidae,plant feeders,3,1,h3,

In [46]:
merge_table = ecology.merge(clc_lifehistory_agg, how='left', left_on='Species', right_on='Parasite.species')

In [47]:
merge_table = merge_table.merge(clc_hosts_agg, how='left', left_on='Species', right_on='Parasite.species', suffixes=('', '_hosts'))

In [49]:
merge_table = merge_table.merge(nemaplex, how='left', left_on='Parasite.genus', right_on='Species', suffixes=('', '_np'))

In [51]:
merge_table.head(200)

,PC1 projection FourFoldPCA (from r strategy to K strategy),Species,Group (Family),Taxonomy,"cp scaling (1 - colonizer, 5 - persister)","Type (free, parasite, facultative)",Feeding (based on Family),"Main host (vertebrate, plant, aquatic, invertebrate, insect)",All hosts,Host organs,...,Journal_hosts,Volume_hosts,Pages_hosts,Species_np,Family,PutativeFeeding,Cpscaling,FeedingGroup,FunctionalGuild,InternalCode
0,-2.35,Dirofilaria repens,Paratylenchus,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"dogs, cats",heart,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-2.20,Parastrongyloides trichosuri,Strongyloididae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-2.20,Dirofilaria sp. hongkongensis,Onchocercidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"dogs, humans","heart, lungs",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-2.18,Strongyloides stercoralis,Strongyloididae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"humans, mammals",small intestine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-2.18,Setaria digitata,Setariidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"cattle, sheep, goats, pigs, horses",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,5.13,Trichinella murrelli,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,5.23,Trichinella nelsoni,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,5.37,Trichinella nativa,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,5.42,Trichinella spiralis,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,5.50,Trichinella pseudospiralis,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
merge_table.to_csv('../../Body/3Results/15_MergingDatabases.csv', sep=';')

In [3]:
merge_table = pd.read_csv('../../Body/3Results/15_MergingDatabases.csv', sep=';')

In [ ]:
# stats for ecology df

In [7]:
gr_1 = list(ecology[ecology['cp scaling (1 - colonizer, 5 - persister)'] == 1]['PC1 projection FourFoldPCA (from r strategy to K strategy)'])

In [8]:
gr_5 = list(ecology[ecology['cp scaling (1 - colonizer, 5 - persister)'] == 5]['PC1 projection FourFoldPCA (from r strategy to K strategy)'])

In [9]:
len(gr_1) + len(gr_5)

29

In [20]:
from scipy.stats import mannwhitneyu

In [63]:
mannwhitneyu(gr_1, gr_5)

MannwhitneyuResult(statistic=1.0, pvalue=0.0007292716860932202)

In [14]:
trd_pca = pd.read_csv('../../Body/3Results/11_PCA_3rd_Pos_projections.csv')
trd_pca

                     Unnamed: 0       PC1       PC2       PC3           PC4
0      Acanthocheilonema viteae -1.912149 -0.068217 -0.670541 -2.220446e-16
1           Acrobeloides varius  0.866524  0.883946  0.347221  1.387779e-17
2    Aelurostrongylus abstrusus -1.543053 -0.922018  0.126565 -2.220446e-16
3         Agamermis sp. BH-2006  1.795231  0.979864  0.359190 -4.996004e-16
4      Allodiplogaster sudhausi  0.666609  0.815134  0.324141 -4.302114e-16
..                          ...       ...       ...       ...           ...
179         Wellcomia siamensis -0.974390  0.616047 -0.081498 -4.718448e-16
180        Wuchereria bancrofti -1.482932  0.244096 -0.744292 -4.579670e-16
181        Xiphinema americanum  2.057019 -0.989935  0.001951 -5.551115e-17
182        Xiphinema pachtaicum  0.985628 -0.872671  0.362625  3.053113e-16
183            Xiphinema rivesi  1.889541 -0.106891  0.261513 -4.440892e-16

[184 rows x 5 columns]

In [111]:
eco_trd = ecology.merge(trd_pca, how='left', left_on='Species', right_on='Unnamed: 0')

In [112]:
eco_trd

,PC1 projection FourFoldPCA (from r strategy to K strategy),Species,Group (Family),Taxonomy,"cp scaling (1 - colonizer, 5 - persister)","Type (free, parasite, facultative)",Feeding (based on Family),"Main host (vertebrate, plant, aquatic, invertebrate, insect)",All hosts,Host organs,...,Adult body size (length),intermediate <=> final host,Comment / life cycle,link to life-cycle,sex,Unnamed: 0,PC1,PC2,PC3,PC4
0,-2.35,Dirofilaria repens,Paratylenchus,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"dogs, cats",heart,...,NaN,mosquito => dog,infected mosquito [numerous == r?] introduces ...,https://www.cdc.gov/parasites/dirofilariasis/b...,NaN,Dirofilaria repens,-2.083091,0.584539,-0.886866,-5.551115e-17
1,-2.20,Parastrongyloides trichosuri,Strongyloididae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,free <=> parasite,"a nematode parasite of mammals, Parastrongyloi...",https://pubmed.ncbi.nlm.nih.gov/16500655/,NaN,Parastrongyloides trichosuri,-1.788322,0.605287,-0.844255,-5.828671e-16
2,-2.20,Dirofilaria sp. hongkongensis,Onchocercidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"dogs, humans","heart, lungs",...,NaN,NaN,NaN,NaN,NaN,Dirofilaria sp. hongkongensis,-1.783086,0.725521,-0.943872,-8.049117e-16
3,-2.18,Strongyloides stercoralis,Strongyloididae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"humans, mammals",small intestine,...,NaN,free <=> parasite,сложным и уникальным для нематод циклом развит...,https://ru.wikipedia.org/wiki/Strongyloides_st...,NaN,Strongyloides stercoralis,-1.738509,1.217876,-1.417831,-4.718448e-16
4,-2.18,Setaria digitata,Setariidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Chrom...",NaN,parasite,animal parasites,vertebrate,"cattle, sheep, goats, pigs, horses",NaN,...,NaN,NaN,NaN,NaN,NaN,Setaria digitata,-2.079223,0.357794,-0.886121,-3.053113e-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,5.13,Trichinella murrelli,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,mammals <=> mammals,Adult worms and encysted larvae develop within...,https://www.cdc.gov/parasites/trichinellosis/b...,NaN,Trichinella murrelli,5.557609,-1.101676,-0.614557,6.661338e-16
180,5.23,Trichinella nelsoni,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,mammals <=> mammals,Adult worms and encysted larvae develop within...,https://www.cdc.gov/parasites/trichinellosis/b...,NaN,Trichinella nelsoni,5.690221,-1.090048,-0.608378,6.661338e-16
181,5.37,Trichinella nativa,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,mammals <=> mammals,Adult worms and encysted larvae develop within...,https://www.cdc.gov/parasites/trichinellosis/b...,NaN,Trichinella nativa,5.485490,-0.979671,-0.564318,4.440892e-16
182,5.42,Trichinella spiralis,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,mammals <=> mammals,Adult worms and encysted larvae develop within...,https://www.cdc.gov/parasites/trichinellosis/b...,NaN,Trichinella spiralis,5.736897,-1.222582,-0.687769,-4.440892e-16
183,5.50,Trichinella pseudospiralis,Trichinellidae,"Eukaryota, Metazoa, Ecdysozoa, Nematoda, Enopl...",NaN,NaN,animal parasites,NaN,NaN,NaN,...,NaN,mammals <=> mammals,Adult worms and encysted larvae develop within...,https://www.cdc.gov/parasites/trichinellosis/b...,Females are 2.2 mm in length; males 1.2 mm,Trichinella pseudospiralis,5.569567,-1.269877,-0.576402,-2.220446e-16

In [113]:
gr_1 = list(eco_trd[eco_trd['cp scaling (1 - colonizer, 5 - persister)'] == 1]['PC1'])

In [114]:
gr_5 = list(eco_trd[eco_trd['cp scaling (1 - colonizer, 5 - persister)'] == 5]['PC1'])

In [19]:
len(gr_1) + len(gr_5)

29

In [115]:
mannwhitneyu(gr_1, gr_5)

MannwhitneyuResult(statistic=4.0, pvalue=0.0013520863627729117)

In [68]:
genomes = pd.read_csv('../../Body/3Results/10_GenomeStatistics.csv', sep=';')

In [69]:
genomes

,ID,Species,Length,Num_A,Num_T,Num_G,Num_C,PrA,PrT,PrG,PrC,Group
0,NC_023208.1,Bursaphelenchus xylophilus,14778,4694,7640,1645,799,31.763432,51.698471,11.131412,5.406686,Other
1,NC_023098.1,Hypodontus macropi,13634,3580,6407,2656,991,26.257885,46.992812,19.480710,7.268593,Other
2,NC_023099.1,Macropicola ocydromi,13659,4018,6338,2382,921,29.416502,46.401640,17.439051,6.742807,Other
3,NC_023262.1,Protostrongylus rufescens,13619,3531,6624,2541,923,25.927014,48.637932,18.657758,6.777296,Other
4,NC_023504.1,Toxascaris leonina,14310,3139,7098,2970,1103,21.935709,49.601677,20.754717,7.707897,Other
...,...,...,...,...,...,...,...,...,...,...,...,...
185,AP017466,Steinernema glaseri,15182,4355,7294,2170,1357,28.685285,48.043736,14.293242,8.938216,Other
186,AP017468,Steinernema litorale,21403,6020,9187,3700,2496,28.126898,42.923889,17.287296,11.661917,Other
187,KM192363,Halicephalobus gingivalis,13735,3742,7200,1763,1030,27.244266,52.420823,12.835821,7.499090,Selected
188,urn.local...ci-d319o1o,Halicephalobus sp. NKZ332,13886,3830,7310,1763,983,27.581737,52.642950,12.696241,7.079072,Selected
189,KX017524.1,Plectus aquatilis,14372,3528,6550,2691,1603,24.547732,45.574729,18.723908,11.153632,Other

In [70]:
genomes = genomes.merge(ecology[['Species', 'cp scaling (1 - colonizer, 5 - persister)']], how='left', left_on='Species', right_on='Species')

In [71]:
genomes.rename(columns = {'cp scaling (1 - colonizer, 5 - persister)' : 'cp scale'}, inplace = True)

In [72]:
gr_1 = list(genomes[genomes['cp scale'] == 1]['PrT'])

In [73]:
gr_5 = list(genomes[genomes['cp scale'] == 5]['PrT'])

In [30]:
len(gr_1) + len(gr_5)

29

In [74]:
mannwhitneyu(gr_1, gr_5)

MannwhitneyuResult(statistic=120.0, pvalue=0.0005911183275260752)

In [33]:
ffold = pd.read_csv('../../Body/3Results/09_FourFoldContent.csv', sep=';')

In [34]:
ffold

,OrganismName,TTT,TTC,TTA,TTG,TCT,TCC,TCA,TCG,TAT,...,GGC,GGA,GGG,TAA,TAG,nnT,nnA,nnG,nnC,Group
0,Acanthocheilonema viteae,620,7,129,255,162,5,5,4,239,...,14,22,44,4,3,79.648843,6.464485,10.454908,3.431764,Other
1,Acrobeloides varius,358,34,379,87,125,1,45,8,183,...,7,68,19,8,4,58.373206,31.499203,6.299841,3.827751,Other
2,Aelurostrongylus abstrusus,531,17,166,347,125,7,8,13,176,...,9,27,43,1,10,68.883610,11.480602,16.547902,3.087886,Other
3,Agamermis sp. BH-2006,293,33,325,50,101,21,74,6,102,...,4,57,13,8,0,46.259220,42.044257,5.479452,6.217071,Other
4,Allodiplogaster sudhausi,400,11,388,113,105,6,28,6,171,...,1,37,42,10,1,60.815308,26.289517,9.983361,2.911814,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,Wellcomia siamensis,643,2,299,207,98,2,11,5,171,...,4,50,38,1,6,72.069597,15.659341,10.897436,1.373626,Other
180,Wuchereria bancrofti,618,14,180,241,149,10,9,2,216,...,8,25,25,7,2,82.430213,8.374384,6.157635,3.037767,Other
181,Xiphinema americanum,88,27,92,27,26,15,20,9,24,...,3,35,10,2,0,36.413043,36.413043,14.855072,12.318841,Other
182,Xiphinema pachtaicum,84,9,64,35,27,7,4,3,16,...,5,10,13,3,2,47.023810,24.107143,17.261905,11.607143,Other
183,Xiphinema rivesi,97,21,108,22,33,12,20,3,25,...,2,36,14,3,0,41.527002,38.361266,12.290503,7.821229,Other

In [37]:
ffold = ffold.merge(ecology[['Species', 'cp scaling (1 - colonizer, 5 - persister)']], how='left', left_on='OrganismName', right_on='Species')

In [38]:
ffold.rename(columns = {'cp scaling (1 - colonizer, 5 - persister)' : 'cp scale'}, inplace = True)

In [88]:
gr_1 = list(ffold[ffold['cp scale'] == 1]['nnT'])

In [89]:
gr_5 = list(ffold[ffold['cp scale'] == 5]['nnT'])

In [90]:
len(gr_1) + len(gr_5)

29

In [43]:
mannwhitneyu(gr_1, gr_5)

MannwhitneyuResult(statistic=119.0, pvalue=0.0007303762664803503)

In [75]:
trd_pos = pd.read_csv('../../Body/3Results/09_3rd_Pos_Content.csv', sep=';')

In [76]:
trd_pos

,OrganismName,TTT,TTC,TTA,TTG,TCT,TCC,TCA,TCG,TAT,...,GGC,GGA,GGG,TAA,TAG,nnT,nnA,nnG,nnC,Group
0,Acanthocheilonema viteae,620,7,129,255,162,5,5,4,239,...,14,22,44,4,3,68.556552,9.835117,19.554527,2.053804,Other
1,Acrobeloides varius,358,34,379,87,125,1,45,8,183,...,7,68,19,8,4,52.177752,35.050029,9.152443,3.619776,Other
2,Aelurostrongylus abstrusus,531,17,166,347,125,7,8,13,176,...,9,27,43,1,10,58.648806,13.948748,24.956319,2.446127,Other
3,Agamermis sp. BH-2006,293,33,325,50,101,21,74,6,102,...,4,57,13,8,0,47.070639,40.944091,5.892200,6.093070,Other
4,Allodiplogaster sudhausi,400,11,388,113,105,6,28,6,171,...,1,37,42,10,1,53.132319,33.518735,10.040984,3.307963,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,Wellcomia siamensis,643,2,299,207,98,2,11,5,171,...,4,50,38,1,6,63.716295,20.838218,14.888628,0.556858,Other
180,Wuchereria bancrofti,618,14,180,241,149,10,9,2,216,...,8,25,25,7,2,67.859204,12.925563,16.474322,2.740912,Other
181,Xiphinema americanum,88,27,92,27,26,15,20,9,24,...,3,35,10,2,0,37.457627,34.491525,14.067797,13.983051,Other
182,Xiphinema pachtaicum,84,9,64,35,27,7,4,3,16,...,5,10,13,3,2,42.804428,30.504305,17.712177,8.979090,Other
183,Xiphinema rivesi,97,21,108,22,33,12,20,3,25,...,2,36,14,3,0,41.624365,37.648054,10.829103,9.898477,Other

In [77]:
trd_pos = trd_pos.merge(ecology[['Species', 'cp scaling (1 - colonizer, 5 - persister)']], how='left', left_on='OrganismName', right_on='Species')

In [78]:
trd_pos.rename(columns = {'cp scaling (1 - colonizer, 5 - persister)' : 'cp scale'}, inplace = True)

In [85]:
trd_1 = list(trd_pos[trd_pos['cp scale'] == 1]['nnT'])

In [86]:
trd_5 = list(trd_pos[trd_pos['cp scale'] == 5]['nnT'])

In [81]:
len(trd_1) + len(trd_5)

29

In [87]:
mannwhitneyu(trd_1, trd_5)

MannwhitneyuResult(statistic=120.0, pvalue=0.0005911183275260752)

In [92]:
gr_1

[60.8153078202995,
 61.82634730538922,
 56.34920634920635,
 70.92930897537728,
 54.65207193119625,
 71.1284046692607,
 45.859375,
 73.97998460354118,
 62.24165341812401,
 69.61538461538461,
 67.11675933280381,
 62.58935663224781,
 71.16279069767441,
 64.58333333333334,
 68.9873417721519,
 81.33704735376045,
 80.50373134328358,
 84.21052631578947,
 86.01959038290295,
 82.61986301369863,
 68.5737308622079,
 68.5737308622079,
 62.794918330308526,
 49.18166939443535]

In [94]:
trd_1

[53.13231850117096,
 55.92775997669677,
 53.613053613053616,
 59.39411593358579,
 53.46736596736597,
 59.3067288086222,
 49.5484998543548,
 61.549665016020974,
 55.21561771561772,
 59.19021264200408,
 57.50510055377441,
 56.58508158508159,
 59.68540635013108,
 58.20460507140776,
 58.84066414214972,
 69.01740926526999,
 68.1724239740183,
 67.39622641509435,
 68.65715117972618,
 66.97432939140468,
 58.29935934769948,
 58.29935934769948,
 57.82392512430536,
 48.46983386767707]

In [96]:
import numpy as np

In [ ]:
from

In [109]:
np.mean(gr_5) - np.mean(gr_1)

-30.05772972527687

In [110]:
np.mean(trd_5) - np.mean(trd_1)

-22.311160928181145